// Larger local named-color dataset for Build Your Dream.
// Sources: the built-in X11 rgb.txt named color list plus a local subset of
// the XKCD color survey. Each entry keeps a real source name and its exact HEX
// value so displayed names, copied HEX codes, and card backgrounds all come
// from the same source row.
// Add more named-color sources here as { name, hex } entries when needed.
window.dreamNamedColors = [
  { name: 'Snow', hex: "#FFFAFA" },
  { name: 'Ghost White', hex: "#F8F8FF" },
  { name: 'White Smoke', hex: "#F5F5F5" },
  { name: 'Gainsboro', hex: "#DCDCDC" },
  { name: 'Floral White', hex: "#FFFAF0" },
  { name: 'Old Lace', hex: "#FDF5E6" },
  { name: 'Linen', hex: "#FAF0E6" },
  { name: 'Antique White', hex: "#FAEBD7" },
  { name: 'Papaya Whip', hex: "#FFEFD5" },
  { name: 'Blanched Almond', hex: "#FFEBCD" },
  { name: 'Bisque', hex: "#FFE4C4" },
  { name: 'Peach Puff', hex: "#FFDAB9" },
  { name: 'Navajo White', hex: "#FFDEAD" },
  { name: 'Moccasin', hex: "#FFE4B5" },
  { name: 'Cornsilk', hex: "#FFF8DC" },
  { name: 'Ivory', hex: "#FFFFF0" },
  { name: 'Lemon Chiffon', hex: "#FFFACD" },
  { name: 'Seashell', hex: "#FFF5EE" },
  { name: 'Honeydew', hex: "#F0FFF0" },
  { name: 'Mint Cream', hex: "#F5FFFA" },
  { name: 'Azure', hex: "#F0FFFF" },
  { name: 'Alice Blue', hex: "#F0F8FF" },
  { name: 'Lavender', hex: "#E6E6FA" },
  { name: 'Lavender Blush', hex: "#FFF0F5" },
  { name: 'Misty Rose', hex: "#FFE4E1" },
  { name: 'White', hex: "#FFFFFF" },
  { name: 'Black', hex: "#000000" },
  { name: 'Dark Slate Gray', hex: "#2F4F4F" },
  { name: 'Dark Slate Grey', hex: "#2F4F4F" },
  { name: 'Dim Gray', hex: "#696969" },
  { name: 'Dim Grey', hex: "#696969" },
  { name: 'Slate Gray', hex: "#708090" },
  { name: 'Slate Grey', hex: "#708090" },
  { name: 'Light Slate Gray', hex: "#778899" },
  { name: 'Light Slate Grey', hex: "#778899" },
  { name: 'Gray', hex: "#BEBEBE" },
  { name: 'Grey', hex: "#BEBEBE" },
  { name: 'Light Grey', hex: "#D3D3D3" },
  { name: 'Light Gray', hex: "#D3D3D3" },
  { name: 'Midnight Blue', hex: "#191970" },
  { name: 'Navy', hex: "#000080" },
  { name: 'Navy Blue', hex: "#000080" },
  { name: 'Cornflower Blue', hex: "#6495ED" },
  { name: 'Dark Slate Blue', hex: "#483D8B" },
  { name: 'Slate Blue', hex: "#6A5ACD" },
  { name: 'Medium Slate Blue', hex: "#7B68EE" },
  { name: 'Light Slate Blue', hex: "#8470FF" },
  { name: 'Medium Blue', hex: "#0000CD" },
  { name: 'Royal Blue', hex: "#4169E1" },
  { name: 'Blue', hex: "#0000FF" },
  { name: 'Dodger Blue', hex: "#1E90FF" },
  { name: 'Deep Sky Blue', hex: "#00BFFF" },
  { name: 'Sky Blue', hex: "#87CEEB" },
  { name: 'Light Sky Blue', hex: "#87CEFA" },
  { name: 'Steel Blue', hex: "#4682B4" },
  { name: 'Light Steel Blue', hex: "#B0C4DE" },
  { name: 'Light Blue', hex: "#ADD8E6" },
  { name: 'Powder Blue', hex: "#B0E0E6" },
  { name: 'Pale Turquoise', hex: "#AFEEEE" },
  { name: 'Dark Turquoise', hex: "#00CED1" },
  { name: 'Medium Turquoise', hex: "#48D1CC" },
  { name: 'Turquoise', hex: "#40E0D0" },
  { name: 'Cyan', hex: "#00FFFF" },
  { name: 'Light Cyan', hex: "#E0FFFF" },
  { name: 'Cadet Blue', hex: "#5F9EA0" },
  { name: 'Medium Aquamarine', hex: "#66CDAA" },
  { name: 'Aquamarine', hex: "#7FFFD4" },
  { name: 'Dark Green', hex: "#006400" },
  { name: 'Dark Olive Green', hex: "#556B2F" },
  { name: 'Dark Sea Green', hex: "#8FBC8F" },
  { name: 'Sea Green', hex: "#2E8B57" },
  { name: 'Medium Sea Green', hex: "#3CB371" },
  { name: 'Light Sea Green', hex: "#20B2AA" },
  { name: 'Pale Green', hex: "#98FB98" },
  { name: 'Spring Green', hex: "#00FF7F" },
  { name: 'Lawn Green', hex: "#7CFC00" },
  { name: 'Green', hex: "#00FF00" },
  { name: 'Chartreuse', hex: "#7FFF00" },
  { name: 'Medium Spring Green', hex: "#00FA9A" },
  { name: 'Green Yellow', hex: "#ADFF2F" },
  { name: 'Lime Green', hex: "#32CD32" },
  { name: 'Yellow Green', hex: "#9ACD32" },
  { name: 'Forest Green', hex: "#228B22" },
  { name: 'Olive Drab', hex: "#6B8E23" },
  { name: 'Dark Khaki', hex: "#BDB76B" },
  { name: 'Khaki', hex: "#F0E68C" },
  { name: 'Pale Goldenrod', hex: "#EEE8AA" },
  { name: 'Light Goldenrod Yellow', hex: "#FAFAD2" },
  { name: 'Light Yellow', hex: "#FFFFE0" },
  { name: 'Yellow', hex: "#FFFF00" },
  { name: 'Gold', hex: "#FFD700" },
  { name: 'Light Goldenrod', hex: "#EEDD82" },
  { name: 'Goldenrod', hex: "#DAA520" },
  { name: 'Dark Goldenrod', hex: "#B8860B" },
  { name: 'Rosy Brown', hex: "#BC8F8F" },
  { name: 'Indian Red', hex: "#CD5C5C" },
  { name: 'Saddle Brown', hex: "#8B4513" },
  { name: 'Sienna', hex: "#A0522D" },
  { name: 'Peru', hex: "#CD853F" },
  { name: 'Burlywood', hex: "#DEB887" },
  { name: 'Beige', hex: "#F5F5DC" },
  { name: 'Wheat', hex: "#F5DEB3" },
  { name: 'Sandy Brown', hex: "#F4A460" },
  { name: 'Tan', hex: "#D2B48C" },
  { name: 'Chocolate', hex: "#D2691E" },
  { name: 'Firebrick', hex: "#B22222" },
  { name: 'Brown', hex: "#A52A2A" },
  { name: 'Dark Salmon', hex: "#E9967A" },
  { name: 'Salmon', hex: "#FA8072" },
  { name: 'Light Salmon', hex: "#FFA07A" },
  { name: 'Orange', hex: "#FFA500" },
  { name: 'Dark Orange', hex: "#FF8C00" },
  { name: 'Coral', hex: "#FF7F50" },
  { name: 'Light Coral', hex: "#F08080" },
  { name: 'Tomato', hex: "#FF6347" },
  { name: 'Orange Red', hex: "#FF4500" },
  { name: 'Red', hex: "#FF0000" },
  { name: 'Hot Pink', hex: "#FF69B4" },
  { name: 'Deep Pink', hex: "#FF1493" },
  { name: 'Pink', hex: "#FFC0CB" },
  { name: 'Light Pink', hex: "#FFB6C1" },
  { name: 'Pale Violet Red', hex: "#DB7093" },
  { name: 'Maroon', hex: "#B03060" },
  { name: 'Medium Violet Red', hex: "#C71585" },
  { name: 'Violet Red', hex: "#D02090" },
  { name: 'Magenta', hex: "#FF00FF" },
  { name: 'Violet', hex: "#EE82EE" },
  { name: 'Plum', hex: "#DDA0DD" },
  { name: 'Orchid', hex: "#DA70D6" },
  { name: 'Medium Orchid', hex: "#BA55D3" },
  { name: 'Dark Orchid', hex: "#9932CC" },
  { name: 'Dark Violet', hex: "#9400D3" },
  { name: 'Blue Violet', hex: "#8A2BE2" },
  { name: 'Purple', hex: "#A020F0" },
  { name: 'Medium Purple', hex: "#9370DB" },
  { name: 'Thistle', hex: "#D8BFD8" },
  { name: 'Debian Red', hex: "#D70751" },
  { name: 'Dark Grey', hex: "#A9A9A9" },
  { name: 'Dark Gray', hex: "#A9A9A9" },
  { name: 'Dark Blue', hex: "#00008B" },
  { name: 'Dark Cyan', hex: "#008B8B" },
  { name: 'Dark Magenta', hex: "#8B008B" },
  { name: 'Dark Red', hex: "#8B0000" },
  { name: 'Light Green', hex: "#90EE90" },
  // Additional real named colors from the XKCD color survey (CC0).
  { name: 'Purple', hex: "#7E1E9C", source: 'xkcd color survey' },
  { name: 'Green', hex: "#15B01A", source: 'xkcd color survey' },
  { name: 'Blue', hex: "#0343DF", source: 'xkcd color survey' },
  { name: 'Pink', hex: "#FF81C0", source: 'xkcd color survey' },
  { name: 'Brown', hex: "#653700", source: 'xkcd color survey' },
  { name: 'Red', hex: "#E50000", source: 'xkcd color survey' },
  { name: 'Light Blue', hex: "#95D0FC", source: 'xkcd color survey' },
  { name: 'Teal', hex: "#029386", source: 'xkcd color survey' },
  { name: 'Orange', hex: "#F97306", source: 'xkcd color survey' },
  { name: 'Light Green', hex: "#96F97B", source: 'xkcd color survey' },
  { name: 'Magenta', hex: "#C20078", source: 'xkcd color survey' },
  { name: 'Yellow', hex: "#FFFF14", source: 'xkcd color survey' },
  { name: 'Sky Blue', hex: "#75BBFD", source: 'xkcd color survey' },
  { name: 'Grey', hex: "#929591", source: 'xkcd color survey' },
  { name: 'Lime Green', hex: "#89FE05", source: 'xkcd color survey' },
  { name: 'Light Purple', hex: "#BF77F6", source: 'xkcd color survey' },
  { name: 'Violet', hex: "#9A0EEA", source: 'xkcd color survey' },
  { name: 'Dark Green', hex: "#033500", source: 'xkcd color survey' },
  { name: 'Turquoise', hex: "#06C2AC", source: 'xkcd color survey' },
  { name: 'Lavender', hex: "#C79FEF", source: 'xkcd color survey' },
  { name: 'Dark Blue', hex: "#00035B", source: 'xkcd color survey' },
  { name: 'Tan', hex: "#D1B26F", source: 'xkcd color survey' },
  { name: 'Cyan', hex: "#00FFFF", source: 'xkcd color survey' },
  { name: 'Aqua', hex: "#13EAC9", source: 'xkcd color survey' },
  { name: 'Forest Green', hex: "#06470C", source: 'xkcd color survey' },
  { name: 'Mauve', hex: "#AE7181", source: 'xkcd color survey' },
  { name: 'Dark Purple', hex: "#35063E", source: 'xkcd color survey' },
  { name: 'Bright Green', hex: "#01FF07", source: 'xkcd color survey' },
  { name: 'Maroon', hex: "#650021", source: 'xkcd color survey' },
  { name: 'Olive', hex: "#6E750E", source: 'xkcd color survey' },
  { name: 'Salmon', hex: "#FF796C", source: 'xkcd color survey' },
  { name: 'Beige', hex: "#E6DAA6", source: 'xkcd color survey' },
  { name: 'Royal Blue', hex: "#0504AA", source: 'xkcd color survey' },
  { name: 'Navy Blue', hex: "#001146", source: 'xkcd color survey' },
  { name: 'Lilac', hex: "#CEA2FD", source: 'xkcd color survey' },
  { name: 'Black', hex: "#000000", source: 'xkcd color survey' },
  { name: 'Hot Pink', hex: "#FF028D", source: 'xkcd color survey' },
  { name: 'Light Brown', hex: "#AD8150", source: 'xkcd color survey' },
  { name: 'Pale Green', hex: "#C7FDB5", source: 'xkcd color survey' },
  { name: 'Peach', hex: "#FFB07C", source: 'xkcd color survey' },
  { name: 'Olive Green', hex: "#677A04", source: 'xkcd color survey' },
  { name: 'Dark Pink', hex: "#CB416B", source: 'xkcd color survey' },
  { name: 'Periwinkle', hex: "#8E82FE", source: 'xkcd color survey' },
  { name: 'Sea Green', hex: "#53FCA1", source: 'xkcd color survey' },
  { name: 'Lime', hex: "#AAFF32", source: 'xkcd color survey' },
  { name: 'Indigo', hex: "#380282", source: 'xkcd color survey' },
  { name: 'Mustard', hex: "#CEB301", source: 'xkcd color survey' },
  { name: 'Light Pink', hex: "#FFD1DF", source: 'xkcd color survey' },
  { name: 'Rose', hex: "#CF6275", source: 'xkcd color survey' },
  { name: 'Bright Blue', hex: "#0165FC", source: 'xkcd color survey' },
  { name: 'Neon Green', hex: "#0CFF0C", source: 'xkcd color survey' },
  { name: 'Burnt Orange', hex: "#C04E01", source: 'xkcd color survey' },
  { name: 'Aquamarine', hex: "#04D8B2", source: 'xkcd color survey' },
  { name: 'Navy', hex: "#01153E", source: 'xkcd color survey' },
  { name: 'Grass Green', hex: "#3F9B0B", source: 'xkcd color survey' },
  { name: 'Pale Blue', hex: "#D0FEFE", source: 'xkcd color survey' },
  { name: 'Dark Red', hex: "#840000", source: 'xkcd color survey' },
  { name: 'Bright Purple', hex: "#BE03FD", source: 'xkcd color survey' },
  { name: 'Yellow Green', hex: "#C0FB2D", source: 'xkcd color survey' },
  { name: 'Baby Blue', hex: "#A2CFFE", source: 'xkcd color survey' },
  { name: 'Gold', hex: "#DBB40C", source: 'xkcd color survey' },
  { name: 'Mint Green', hex: "#8FFF9F", source: 'xkcd color survey' },
  { name: 'Plum', hex: "#580F41", source: 'xkcd color survey' },
  { name: 'Royal Purple', hex: "#4B006E", source: 'xkcd color survey' },
  { name: 'Brick Red', hex: "#8F1402", source: 'xkcd color survey' },
  { name: 'Dark Teal', hex: "#014D4E", source: 'xkcd color survey' },
  { name: 'Burgundy', hex: "#610023", source: 'xkcd color survey' },
  { name: 'Khaki', hex: "#AAA662", source: 'xkcd color survey' },
  { name: 'Blue Green', hex: "#137E6D", source: 'xkcd color survey' },
  { name: 'Seafoam Green', hex: "#7AF9AB", source: 'xkcd color survey' },
  { name: 'Kelly Green', hex: "#02AB2E", source: 'xkcd color survey' },
  { name: 'Pea Green', hex: "#8EAB12", source: 'xkcd color survey' },
  { name: 'Taupe', hex: "#B9A281", source: 'xkcd color survey' },
  { name: 'Dark Brown', hex: "#341C02", source: 'xkcd color survey' },
  { name: 'Deep Purple', hex: "#36013F", source: 'xkcd color survey' },
  { name: 'Chartreuse', hex: "#C1F80A", source: 'xkcd color survey' },
  { name: 'Bright Pink', hex: "#FE01B1", source: 'xkcd color survey' },
  { name: 'Light Orange', hex: "#FDAA48", source: 'xkcd color survey' },
  { name: 'Mint', hex: "#9FFEB0", source: 'xkcd color survey' },
  { name: 'Pastel Green', hex: "#B0FF9D", source: 'xkcd color survey' },
  { name: 'Sand', hex: "#E2CA76", source: 'xkcd color survey' },
  { name: 'Dark Orange', hex: "#C65102", source: 'xkcd color survey' },
  { name: 'Spring Green', hex: "#A9F971", source: 'xkcd color survey' },
  { name: 'Puce', hex: "#A57E52", source: 'xkcd color survey' },
  { name: 'Seafoam', hex: "#80F9AD", source: 'xkcd color survey' },
  { name: 'Grey Blue', hex: "#6B8BA4", source: 'xkcd color survey' },
  { name: 'Army Green', hex: "#4B5D16", source: 'xkcd color survey' },
  { name: 'Dark Grey', hex: "#363737", source: 'xkcd color survey' },
  { name: 'Dark Yellow', hex: "#D5B60A", source: 'xkcd color survey' },
  { name: 'Goldenrod', hex: "#FAC205", source: 'xkcd color survey' },
  { name: 'Slate', hex: "#516572", source: 'xkcd color survey' },
  { name: 'Light Teal', hex: "#90E4C1", source: 'xkcd color survey' },
  { name: 'Rust', hex: "#A83C09", source: 'xkcd color survey' },
  { name: 'Deep Blue', hex: "#040273", source: 'xkcd color survey' },
  { name: 'Pale Pink', hex: "#FFCFDC", source: 'xkcd color survey' },
  { name: 'Cerulean', hex: "#0485D1", source: 'xkcd color survey' },
  { name: 'Light Red', hex: "#FF474C", source: 'xkcd color survey' },
  { name: 'Mustard Yellow', hex: "#D2BD0A", source: 'xkcd color survey' },
  { name: 'Ochre', hex: "#BF9005", source: 'xkcd color survey' },
  { name: 'Pale Yellow', hex: "#FFFF84", source: 'xkcd color survey' },
  { name: 'Crimson', hex: "#8C000F", source: 'xkcd color survey' },
  { name: 'Fuchsia', hex: "#ED0DD9", source: 'xkcd color survey' },
  { name: 'Hunter Green', hex: "#0B4008", source: 'xkcd color survey' },
  { name: 'Blue Grey', hex: "#607C8E", source: 'xkcd color survey' },
  { name: 'Slate Blue', hex: "#5B7C99", source: 'xkcd color survey' },
  { name: 'Pale Purple', hex: "#B790D4", source: 'xkcd color survey' },
  { name: 'Sea Blue', hex: "#047495", source: 'xkcd color survey' },
  { name: 'Pinkish Purple', hex: "#D648D7", source: 'xkcd color survey' },
  { name: 'Light Grey', hex: "#D8DCD6", source: 'xkcd color survey' },
  { name: 'Leaf Green', hex: "#5CA904", source: 'xkcd color survey' },
  { name: 'Light Yellow', hex: "#FFFE7A", source: 'xkcd color survey' },
  { name: 'Eggplant', hex: "#380835", source: 'xkcd color survey' },
  { name: 'Steel Blue', hex: "#5A7D9A", source: 'xkcd color survey' },
  { name: 'Moss Green', hex: "#658B38", source: 'xkcd color survey' },
  { name: 'Robin\'s Egg Blue', hex: "#98EFF9", source: 'xkcd color survey' },
  { name: 'White', hex: "#FFFFFF", source: 'xkcd color survey' },
  { name: 'Grey Green', hex: "#789B73", source: 'xkcd color survey' },
  { name: 'Sage', hex: "#87AE73", source: 'xkcd color survey' },
  { name: 'Brick', hex: "#A03623", source: 'xkcd color survey' },
  { name: 'Burnt Sienna', hex: "#B04E0F", source: 'xkcd color survey' },
  { name: 'Reddish Brown', hex: "#7F2B0A", source: 'xkcd color survey' },
  { name: 'Cream', hex: "#FFFFC2", source: 'xkcd color survey' },
  { name: 'Coral', hex: "#FC5A50", source: 'xkcd color survey' },
  { name: 'Ocean Blue', hex: "#03719C", source: 'xkcd color survey' },
  { name: 'Greenish', hex: "#40A368", source: 'xkcd color survey' },
  { name: 'Dark Magenta', hex: "#960056", source: 'xkcd color survey' },
  { name: 'Red Orange', hex: "#FD3C06", source: 'xkcd color survey' },
  { name: 'Bluish Purple', hex: "#703BE7", source: 'xkcd color survey' },
  { name: 'Midnight Blue', hex: "#020035", source: 'xkcd color survey' },
  { name: 'Light Violet', hex: "#D6B4FC", source: 'xkcd color survey' },
  { name: 'Dusty Rose', hex: "#C0737A", source: 'xkcd color survey' },
  { name: 'Medium Blue', hex: "#2C6FBB", source: 'xkcd color survey' },
  { name: 'Greenish Yellow', hex: "#CDFD02", source: 'xkcd color survey' },
  { name: 'Yellowish Green', hex: "#B0DD16", source: 'xkcd color survey' },
  { name: 'Purplish Blue', hex: "#601EF9", source: 'xkcd color survey' },
  { name: 'Greyish Blue', hex: "#5E819D", source: 'xkcd color survey' },
  { name: 'Grape', hex: "#6C3461", source: 'xkcd color survey' },
  { name: 'Light Olive', hex: "#ACBF69", source: 'xkcd color survey' },
  { name: 'Cornflower Blue', hex: "#5170D7", source: 'xkcd color survey' },
  { name: 'Pinkish Red', hex: "#F10C45", source: 'xkcd color survey' },
  { name: 'Bright Red', hex: "#FF000D", source: 'xkcd color survey' },
  { name: 'Azure', hex: "#069AF3", source: 'xkcd color survey' },
  { name: 'Blue Purple', hex: "#5729CE", source: 'xkcd color survey' },
  { name: 'Dark Turquoise', hex: "#045C5A", source: 'xkcd color survey' },
  { name: 'Electric Blue', hex: "#0652FF", source: 'xkcd color survey' },
  { name: 'Off White', hex: "#FFFFE4", source: 'xkcd color survey' },
  { name: 'Powder Blue', hex: "#B1D1FC", source: 'xkcd color survey' },
  { name: 'Wine', hex: "#80013F", source: 'xkcd color survey' },
  { name: 'Dull Green', hex: "#74A662", source: 'xkcd color survey' },
  { name: 'Apple Green', hex: "#76CD26", source: 'xkcd color survey' },
  { name: 'Light Turquoise', hex: "#7EF4CC", source: 'xkcd color survey' },
  { name: 'Neon Purple', hex: "#BC13FE", source: 'xkcd color survey' },
  { name: 'Cobalt', hex: "#1E488F", source: 'xkcd color survey' },
  { name: 'Pinkish', hex: "#D46A7E", source: 'xkcd color survey' },
  { name: 'Olive Drab', hex: "#6F7632", source: 'xkcd color survey' },
  { name: 'Dark Cyan', hex: "#0A888A", source: 'xkcd color survey' },
  { name: 'Purple Blue', hex: "#632DE9", source: 'xkcd color survey' },
  { name: 'Dark Violet', hex: "#34013F", source: 'xkcd color survey' },
  { name: 'Dark Lavender', hex: "#856798", source: 'xkcd color survey' },
  { name: 'Pale Orange', hex: "#FFA756", source: 'xkcd color survey' },
  { name: 'Greenish Blue', hex: "#0B8B87", source: 'xkcd color survey' },
  { name: 'Dark Tan', hex: "#AF884A", source: 'xkcd color survey' },
  { name: 'Green Blue', hex: "#06B48B", source: 'xkcd color survey' },
  { name: 'Bluish Green', hex: "#10A674", source: 'xkcd color survey' },
  { name: 'Pastel Blue', hex: "#A2BFFE", source: 'xkcd color survey' },
  { name: 'Moss', hex: "#769958", source: 'xkcd color survey' },
  { name: 'Grass', hex: "#5CAC2D", source: 'xkcd color survey' },
  { name: 'Deep Pink', hex: "#CB0162", source: 'xkcd color survey' },
  { name: 'Blood Red', hex: "#980002", source: 'xkcd color survey' },
  { name: 'Sage Green', hex: "#88B378", source: 'xkcd color survey' },
  { name: 'Aqua Blue', hex: "#02D8E9", source: 'xkcd color survey' },
  { name: 'Terracotta', hex: "#CA6641", source: 'xkcd color survey' },
  { name: 'Pastel Purple', hex: "#CAA0FF", source: 'xkcd color survey' },
  { name: 'Sienna', hex: "#A9561E", source: 'xkcd color survey' },
  { name: 'Dark Olive', hex: "#373E02", source: 'xkcd color survey' },
  { name: 'Green Yellow', hex: "#C9FF27", source: 'xkcd color survey' },
  { name: 'Scarlet', hex: "#BE0119", source: 'xkcd color survey' },
  { name: 'Greyish Green', hex: "#82A67D", source: 'xkcd color survey' },
  { name: 'Chocolate', hex: "#3D1C02", source: 'xkcd color survey' },
  { name: 'Blue Violet', hex: "#5D06E9", source: 'xkcd color survey' },
  { name: 'Cornflower', hex: "#6A79F7", source: 'xkcd color survey' },
  { name: 'Baby Pink', hex: "#FFB7CE", source: 'xkcd color survey' },
  { name: 'Charcoal', hex: "#343837", source: 'xkcd color survey' },
  { name: 'Pine Green', hex: "#0A481E", source: 'xkcd color survey' },
  { name: 'Pumpkin', hex: "#E17701", source: 'xkcd color survey' },
  { name: 'Tangerine', hex: "#FF9408", source: 'xkcd color survey' },
  { name: 'Salmon Pink', hex: "#FE7B7C", source: 'xkcd color survey' },
  { name: 'Aqua Green', hex: "#12E193", source: 'xkcd color survey' },
  { name: 'Raspberry', hex: "#B00149", source: 'xkcd color survey' },
  { name: 'Greyish Purple', hex: "#887191", source: 'xkcd color survey' },
  { name: 'Rose Pink', hex: "#F7879A", source: 'xkcd color survey' },
  { name: 'Neon Pink', hex: "#FE019A", source: 'xkcd color survey' },
  { name: 'Cobalt Blue', hex: "#030AA7", source: 'xkcd color survey' },
  { name: 'Orange Brown', hex: "#BE6400", source: 'xkcd color survey' },
  { name: 'Deep Red', hex: "#9A0200", source: 'xkcd color survey' },
  { name: 'Orange Red', hex: "#FD411E", source: 'xkcd color survey' },
  { name: 'Dirty Yellow', hex: "#CDC50A", source: 'xkcd color survey' },
  { name: 'Orchid', hex: "#C875C4", source: 'xkcd color survey' },
  { name: 'Reddish Pink', hex: "#FE2C54", source: 'xkcd color survey' },
  { name: 'Reddish Purple', hex: "#910951", source: 'xkcd color survey' },
  { name: 'Yellow Orange', hex: "#FCB001", source: 'xkcd color survey' },
  { name: 'Light Cyan', hex: "#ACFFFC", source: 'xkcd color survey' },
  { name: 'Sky', hex: "#82CAFC", source: 'xkcd color survey' },
  { name: 'Light Magenta', hex: "#FA5FF7", source: 'xkcd color survey' },
  { name: 'Pale Red', hex: "#D9544D", source: 'xkcd color survey' },
  { name: 'Emerald', hex: "#01A049", source: 'xkcd color survey' },
  { name: 'Jade', hex: "#1FA774", source: 'xkcd color survey' },
  { name: 'Dark Beige', hex: "#AC9362", source: 'xkcd color survey' },
  { name: 'Greenish Grey', hex: "#96AE8D", source: 'xkcd color survey' },
  { name: 'Dark Salmon', hex: "#C85A53", source: 'xkcd color survey' },
  { name: 'Purplish Pink', hex: "#CE5DAE", source: 'xkcd color survey' },
  { name: 'Dark Aqua', hex: "#05696B", source: 'xkcd color survey' },
  { name: 'Brownish Orange', hex: "#CB7723", source: 'xkcd color survey' },
  { name: 'Light Olive Green', hex: "#A4BE5C", source: 'xkcd color survey' },
  { name: 'Light Aqua', hex: "#8CFFDB", source: 'xkcd color survey' },
  { name: 'Clay', hex: "#B66A50", source: 'xkcd color survey' },
  { name: 'Medium Green', hex: "#39AD48", source: 'xkcd color survey' },
  { name: 'Burnt Umber', hex: "#A0450E", source: 'xkcd color survey' },
  { name: 'Dull Blue', hex: "#49759C", source: 'xkcd color survey' },
  { name: 'Pale Brown', hex: "#B1916E", source: 'xkcd color survey' },
  { name: 'Emerald Green', hex: "#028F1E", source: 'xkcd color survey' },
  { name: 'Brownish', hex: "#9C6D57", source: 'xkcd color survey' },
  { name: 'Mud', hex: "#735C12", source: 'xkcd color survey' },
  { name: 'Dark Rose', hex: "#B5485D", source: 'xkcd color survey' },
  { name: 'Brownish Red', hex: "#9E3623", source: 'xkcd color survey' },
  { name: 'Pink Purple', hex: "#DB4BDA", source: 'xkcd color survey' },
  { name: 'Pinky Purple', hex: "#C94CBE", source: 'xkcd color survey' },
  { name: 'Camo Green', hex: "#526525", source: 'xkcd color survey' },
  { name: 'Faded Green', hex: "#7BB274", source: 'xkcd color survey' },
  { name: 'Dusty Pink', hex: "#D58A94", source: 'xkcd color survey' },
  { name: 'Purple Pink', hex: "#E03FD8", source: 'xkcd color survey' },
  { name: 'Deep Green', hex: "#02590F", source: 'xkcd color survey' },
  { name: 'Reddish Orange', hex: "#F8481C", source: 'xkcd color survey' },
  { name: 'Mahogany', hex: "#4A0100", source: 'xkcd color survey' },
  { name: 'Aubergine', hex: "#3D0734", source: 'xkcd color survey' },
  { name: 'Dull Pink', hex: "#D5869D", source: 'xkcd color survey' },
  { name: 'Evergreen', hex: "#05472A", source: 'xkcd color survey' },
  { name: 'Dark Sky Blue', hex: "#448EE4", source: 'xkcd color survey' },
  { name: 'Very Light Green', hex: "#D1FFBD", source: 'xkcd color survey' },
  { name: 'Pastel Pink', hex: "#FFBACD", source: 'xkcd color survey' },
  { name: 'Grey Purple', hex: "#826D8C", source: 'xkcd color survey' },
  { name: 'Very Light Blue', hex: "#D5FFFF", source: 'xkcd color survey' },
  { name: 'Dark Mauve', hex: "#874C62", source: 'xkcd color survey' },
  { name: 'Cadet Blue', hex: "#4E7496", source: 'xkcd color survey' },
  { name: 'Ice Blue', hex: "#D7FFFE", source: 'xkcd color survey' },
  { name: 'Light Tan', hex: "#FBEEAC", source: 'xkcd color survey' },
  { name: 'Neon Blue', hex: "#04D9FF", source: 'xkcd color survey' },
  { name: 'Wine Red', hex: "#7B0323", source: 'xkcd color survey' },
  { name: 'Chocolate Brown', hex: "#411900", source: 'xkcd color survey' },
  { name: 'Dull Purple', hex: "#84597E", source: 'xkcd color survey' },
  { name: 'Yellow Brown', hex: "#B79400", source: 'xkcd color survey' },
  { name: 'Denim', hex: "#3B638C", source: 'xkcd color survey' },
  { name: 'Eggshell', hex: "#FFFFD4", source: 'xkcd color survey' },
  { name: 'Jungle Green', hex: "#048243", source: 'xkcd color survey' },
  { name: 'Dark Peach', hex: "#DE7E5D", source: 'xkcd color survey' },
  { name: 'Umber', hex: "#B26400", source: 'xkcd color survey' },
  { name: 'Light Lavender', hex: "#DFC5FE", source: 'xkcd color survey' },
  { name: 'Bright Yellow', hex: "#FFFD01", source: 'xkcd color survey' },
  { name: 'Golden Yellow', hex: "#FEC615", source: 'xkcd color survey' },
  { name: 'Dusty Blue', hex: "#5A86AD", source: 'xkcd color survey' },
  { name: 'Electric Green', hex: "#21FC0D", source: 'xkcd color survey' },
  { name: 'Slate Grey', hex: "#59656D", source: 'xkcd color survey' },
  { name: 'Teal Green', hex: "#25A36F", source: 'xkcd color survey' },
  { name: 'Marine Blue', hex: "#01386A", source: 'xkcd color survey' },
  { name: 'Avocado', hex: "#90B134", source: 'xkcd color survey' },
  { name: 'Terra Cotta', hex: "#C9643B", source: 'xkcd color survey' },
  { name: 'Dusty Purple', hex: "#825F87", source: 'xkcd color survey' },
  { name: 'Light Maroon', hex: "#A24857", source: 'xkcd color survey' },
  { name: 'Reddish', hex: "#C44240", source: 'xkcd color survey' },
  { name: 'Dark Lilac', hex: "#9C6DA5", source: 'xkcd color survey' },
  { name: 'Dark Periwinkle', hex: "#665FD1", source: 'xkcd color survey' },
  { name: 'Bluish Grey', hex: "#748B97", source: 'xkcd color survey' },
  { name: 'Ultramarine', hex: "#2000B1", source: 'xkcd color survey' },
  { name: 'Forest', hex: "#0B5509", source: 'xkcd color survey' },
  { name: 'Bright Teal', hex: "#01F9C6", source: 'xkcd color survey' },
  { name: 'Light Sky Blue', hex: "#C6FCFF", source: 'xkcd color survey' },
  { name: 'Periwinkle Blue', hex: "#8F99FB", source: 'xkcd color survey' },
  { name: 'Pale Violet', hex: "#CEAEFA", source: 'xkcd color survey' },
  { name: 'True Blue', hex: "#010FCC", source: 'xkcd color survey' },
  { name: 'Green Grey', hex: "#77926F", source: 'xkcd color survey' },
  { name: 'Grey Brown', hex: "#7F7053", source: 'xkcd color survey' },
  { name: 'Dark Olive Green', hex: "#3C4D03", source: 'xkcd color survey' },
  { name: 'Apricot', hex: "#FFB16D", source: 'xkcd color survey' },
  { name: 'Faded Purple', hex: "#916E99", source: 'xkcd color survey' },
  { name: 'Cerise', hex: "#DE0C62", source: 'xkcd color survey' },
  { name: 'Khaki Green', hex: "#728639", source: 'xkcd color survey' },
  { name: 'Burnt Red', hex: "#9F2305", source: 'xkcd color survey' },
  { name: 'Light Forest Green', hex: "#4F9153", source: 'xkcd color survey' },
  { name: 'Violet Blue', hex: "#510AC9", source: 'xkcd color survey' },
  { name: 'Pale Lavender', hex: "#EECFFE", source: 'xkcd color survey' },
  { name: 'Acid Green', hex: "#8FFE09", source: 'xkcd color survey' },
  { name: 'Purple Grey', hex: "#866F85", source: 'xkcd color survey' },
  { name: 'Lemon', hex: "#FDFF52", source: 'xkcd color survey' },
  { name: 'Bright Orange', hex: "#FF5B00", source: 'xkcd color survey' },
  { name: 'Soft Green', hex: "#6FC276", source: 'xkcd color survey' },
  { name: 'Blush', hex: "#F29E8E", source: 'xkcd color survey' },
  { name: 'Yellowish Brown', hex: "#9B7A01", source: 'xkcd color survey' },
  { name: 'Fluorescent Green', hex: "#08FF08", source: 'xkcd color survey' },
  { name: 'Electric Purple', hex: "#AA23FF", source: 'xkcd color survey' },
  { name: 'Steel', hex: "#738595", source: 'xkcd color survey' },
  { name: 'Dull Orange', hex: "#D8863B", source: 'xkcd color survey' },
  { name: 'Muddy Green', hex: "#657432", source: 'xkcd color survey' },
  { name: 'Marigold', hex: "#FCC006", source: 'xkcd color survey' },
  { name: 'Ocean', hex: "#017B92", source: 'xkcd color survey' },
  { name: 'Light Mauve', hex: "#C292A1", source: 'xkcd color survey' },
  { name: 'Bordeaux', hex: "#7B002C", source: 'xkcd color survey' },
  { name: 'Light Blue Green', hex: "#7EFBB3", source: 'xkcd color survey' },
  { name: 'Yellowish', hex: "#FAEE66", source: 'xkcd color survey' },
  { name: 'Light Lime Green', hex: "#B9FF66", source: 'xkcd color survey' },
  { name: 'Drab Green', hex: "#749551", source: 'xkcd color survey' },
  { name: 'Faded Blue', hex: "#658CBB", source: 'xkcd color survey' },
  { name: 'Dark Forest Green', hex: "#002D04", source: 'xkcd color survey' },
  { name: 'Hot Purple', hex: "#CB00F5", source: 'xkcd color survey' },
  { name: 'Dark Maroon', hex: "#3C0008", source: 'xkcd color survey' },
  { name: 'Swamp Green', hex: "#748500", source: 'xkcd color survey' },
  { name: 'Light Indigo', hex: "#6D5ACF", source: 'xkcd color survey' },
  { name: 'Lightish Blue', hex: "#3D7AFD", source: 'xkcd color survey' },
  { name: 'Teal Blue', hex: "#01889F", source: 'xkcd color survey' },
  { name: 'Denim Blue', hex: "#3B5B92", source: 'xkcd color survey' },
  { name: 'Dark Lime Green', hex: "#7EBD01", source: 'xkcd color survey' },
  { name: 'Dull Yellow', hex: "#EEDC5B", source: 'xkcd color survey' },
  { name: 'Pistachio', hex: "#C0FA8B", source: 'xkcd color survey' },
  { name: 'Lemon Yellow', hex: "#FDFF38", source: 'xkcd color survey' },
  { name: 'Red Violet', hex: "#9E0168", source: 'xkcd color survey' },
  { name: 'Dusky Pink', hex: "#CC7A8B", source: 'xkcd color survey' },
  { name: 'Dirt', hex: "#8A6E45", source: 'xkcd color survey' },
  { name: 'Very Dark Green', hex: "#062E03", source: 'xkcd color survey' },
  { name: 'Medium Purple', hex: "#9E43A2", source: 'xkcd color survey' },
  { name: 'Dark Mustard', hex: "#A88905", source: 'xkcd color survey' },
  { name: 'Bubblegum Pink', hex: "#FE83CC", source: 'xkcd color survey' },
  { name: 'Barbie Pink', hex: "#FE46A5", source: 'xkcd color survey' },
  { name: 'Military Green', hex: "#667C3E", source: 'xkcd color survey' },
  { name: 'Pale Teal', hex: "#82CBB2", source: 'xkcd color survey' },
  { name: 'Bronze', hex: "#A87900", source: 'xkcd color survey' },
  { name: 'Pinky Red', hex: "#FC2647", source: 'xkcd color survey' },
  { name: 'Dull Red', hex: "#BB3F3F", source: 'xkcd color survey' },
  { name: 'Darkish Blue', hex: "#014182", source: 'xkcd color survey' },
  { name: 'Bluish', hex: "#2976BB", source: 'xkcd color survey' },
  { name: 'Dark Gold', hex: "#B59410", source: 'xkcd color survey' },
  { name: 'Yellowy Green', hex: "#BFF128", source: 'xkcd color survey' },
  { name: 'Pine', hex: "#2B5D34", source: 'xkcd color survey' },
  { name: 'Dark Blue Green', hex: "#005249", source: 'xkcd color survey' },
  { name: 'Slate Green', hex: "#658D6D", source: 'xkcd color survey' },
  { name: 'Prussian Blue', hex: "#004577", source: 'xkcd color survey' },
  { name: 'Bright Violet', hex: "#AD0AFD", source: 'xkcd color survey' },
  { name: 'Lighter Purple', hex: "#A55AF4", source: 'xkcd color survey' },
  { name: 'Steel Grey', hex: "#6F828A", source: 'xkcd color survey' },
  { name: 'Russet', hex: "#A13905", source: 'xkcd color survey' },
  { name: 'Vermillion', hex: "#F4320C", source: 'xkcd color survey' },
  { name: 'Greyish Brown', hex: "#7A6A4F", source: 'xkcd color survey' },
  { name: 'Red Purple', hex: "#820747", source: 'xkcd color survey' },
  { name: 'Red Pink', hex: "#FA2A55", source: 'xkcd color survey' },
  { name: 'Bright Turquoise', hex: "#0FFEF9", source: 'xkcd color survey' },
  { name: 'Golden Brown', hex: "#B27A01", source: 'xkcd color survey' },
  { name: 'Cerulean Blue', hex: "#056EEE", source: 'xkcd color survey' },
  { name: 'Soft Blue', hex: "#6488EA", source: 'xkcd color survey' },
  { name: 'Amber', hex: "#FEB308", source: 'xkcd color survey' },
  { name: 'Silver', hex: "#C5C9C7", source: 'xkcd color survey' },
  { name: 'Melon', hex: "#FF7855", source: 'xkcd color survey' },
  { name: 'Cranberry', hex: "#9E003A", source: 'xkcd color survey' },
  { name: 'Ecru', hex: "#FEFFCA", source: 'xkcd color survey' },
  { name: 'Mocha', hex: "#9D7651", source: 'xkcd color survey' },
  { name: 'Bright Magenta', hex: "#FF08E8", source: 'xkcd color survey' },
  { name: 'Coffee', hex: "#A6814C", source: 'xkcd color survey' },
  { name: 'Sepia', hex: "#985E2B", source: 'xkcd color survey' },
  { name: 'Faded Red', hex: "#D3494E", source: 'xkcd color survey' },
  { name: 'Canary Yellow', hex: "#FFFE40", source: 'xkcd color survey' },
  { name: 'Pastel Yellow', hex: "#FFFE71", source: 'xkcd color survey' },
  { name: 'Pale Turquoise', hex: "#A5FBD5", source: 'xkcd color survey' },
  { name: 'Marine', hex: "#042E60", source: 'xkcd color survey' },
  { name: 'Camel', hex: "#C69F59", source: 'xkcd color survey' },
  { name: 'Burnt Yellow', hex: "#D5AB09", source: 'xkcd color survey' },
  { name: 'Cherry Red', hex: "#F7022A", source: 'xkcd color survey' },
  { name: 'Soft Pink', hex: "#FDB0C0", source: 'xkcd color survey' },
];
